### ISSUE TITLE
PAS_DEBUG=1 pas cordova:up

### ISSUE THREAD

**Issue by faridlab** [reekoheek/pas-cordova#2]
``` bash
PAS_DEBUG=1 pas cordova:up
Cannot find module '/.../pas-development.json'
0000.118 e| -> TypeError: undefined is not a function
0000.118 e| TypeError: undefined is not a function
0000.118 e|     at module.exports [as exec] (/usr/local/lib/node_modules/pas-cordova/tasks/up.js:9:17)
0000.118 e|     at Task.run (/.../pas/lib/task.js:81:22)
0000.118 e|     at task (/.../pas/lib/task.js:169:42)
0000.118 e|     at Object.module.exports.run (/.../pas/lib/app.js:51:17)
0000.118 e|     at Object.<anonymous> (/.../pas/bin/pas:3:23)
0000.118 e|     at Module._compile (module.js:460:26)
0000.118 e|     at Object.Module._extensions..js (module.js:478:10)
0000.118 e|     at Module.load (module.js:355:32)
0000.118 e|     at Function.Module._load (module.js:310:12)
0000.118 e|     at Function.Module.runMain (module.js:501:10)
0000.131 i| -> ERR
```

**Comment by reekoheek** [comment]
This error because you use earlier pas version. use >= 2.1.1
